# Generated by Django 4.2.4 on 2024-03-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
