# Generated by Django 4.2.4 on 2024-03-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_ru', models.TextField()),
                ('question_text_kz', models.TextField()),
                ('person_type', models.CharField(max_length=50)),
            ],
        ),
    ]
