# Generated by Django 4.2.4 on 2024-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0002_rename_uuid_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
