# Generated by Django 4.2.4 on 2024-03-20 20:23

from django.db import migrations, models
import tandau_app.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0003_customuser_school_customuser_state_customuser_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[tandau_app.validators.PhoneValidator.validate]),
        ),
    ]
