# Generated by Django 5.0.3 on 2024-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0007_remove_video_title_remove_video_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
