# Generated by Django 5.0.3 on 2024-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandau_app', '0008_customuser_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_images'),
        ),
    ]
